version: "3"
services:
  app-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myDB
#    volumes:
#      - ./src/main/db/picture.sql:/docker-entrypoint-initdb.d/picture.sql
  my-web-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - app-db